services:
  - type: web
    name: project27
    env: node
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
