services:
  - type: web
    name: project27
    env: node
    buildCommand: |
      npm install --legacy-peer-deps && 
      npm install -g serve &&
      npm run build && 
      npx prisma generate &&
      npx prisma db push --accept-data-loss
    startCommand: serve -s build
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: postgresql://project24_db_user:gqXSU51SM9wFzfKcndgRhaqeBQXWQrVk@dpg-ctfccnt2ng1s738idje0-a/project24_db
      - key: CORS_ORIGIN
        value: https://project24-sinw.onrender.com
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://project24-sinw.onrender.com
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
